# ---- Build Stage ----
    FROM node:16 AS builder

    WORKDIR /app
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    RUN npm run build
    
   # ---- Production Stage ----
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Use custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

    