FROM golang:1.23.2 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/api ./cmd/api

# Set the working directory for building the Go app
WORKDIR /app/cmd/api

# Build the Go application
RUN go build -o main .

# Use distroless for the final image
FROM gcr.io/distroless/base

# Copy the Go binary from the builder stage
COPY --from=builder /app/cmd/api/main /main

# Expose the port the app will run on
EXPOSE 8080

# Run the app
CMD ["/main"]
