# Makefile

.PHONY: run build test clean migrate

# Go related variables
BINARY_NAME=dining-app
MAIN_FILE=cmd/api/main.go

# Database related variables
DB_USER=postgres
DB_PASSWORD=Golu@423
DB_NAME=dining_app
DB_HOST=localhost
DB_PORT=5432

# Build the application
build:
	go build -o bin/$(BINARY_NAME) $(MAIN_FILE)

# Run the application
run:
	go run $(MAIN_FILE)

# Clean build files
clean:
	rm -f bin/$(BINARY_NAME)
	go clean

# Run tests
test:
	go test -v ./...

# Create database
create-db:
	PGPASSWORD=$(DB_PASSWORD) createdb -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER) $(DB_NAME)

# Drop database
drop-db:
	PGPASSWORD=$(DB_PASSWORD) dropdb -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER) $(DB_NAME)

# Run database migrations
migrate:
	PGPASSWORD=$(DB_PASSWORD) psql -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER) -d $(DB_NAME) -f configs/schema.sql

# Reset database (drop, create, migrate)
reset-db: drop-db create-db migrate